/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseweek4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class DBInterface extends javax.swing.JFrame {

    private Connection conn;
    private Statement statement;
    private ResultSet rsall;
    private ResultSet rs;
    /**
     * Creates new form DBGUI
     */
    public DBInterface() throws SQLException {
        try{
    //First we load the driver
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            //Second, we stablish the connection
            conn = DriverManager.getConnection("jdbc:oracle:thin:@dilbert.humber.ca:1521:grok", "n01205440","oracle");
            
            
            statement = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            rsall = statement.executeQuery("select * from STUDENT");

            initComponents();
            
            
        }catch(ClassNotFoundException cnfe){
        
            System.out.println(cnfe.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student number");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address");

        jLabel5.setText("GPA");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setLabel("Find");
        jButton1.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                String studentNumber = jTextField1.getText();
                
                if (!studentNumber.equalsIgnoreCase("") && studentNumber != null){
                
             
                        
                    try {
                        Student std = StudentDB.get(Integer.parseInt(studentNumber));
                        
                        if (std != null){
                        
                            jTextField1.setText(Integer.toString(std.getStudentNumber()));
                            jTextField2.setText(std.getFirstName());
                            jTextField3.setText(std.getLastName()); 
                            jTextField4.setText(std.getAddress());
                            jTextField5.setText(Double.toString(std.getGpa())); 
                        
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
              
            }

        });

        jButton2.setLabel("Display all");
        jButton2.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
 
                String output = "";
                try {
                    List<Student> students = StudentDB.getAll();
                    
                    for (int i = 0; i < students.size(); i++){
                    
                        output += students.get(i).getStudentNumber()+" ";
                        output += students.get(i).getFirstName()+" ";
                        output += students.get(i).getLastName()+" ";
                        output += students.get(i).getAddress()+" ";
                        output += students.get(i).getGpa()+" ";
                        output += "\n";
                    
                    }
                    jTextArea1.setText(output);
                } catch (SQLException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                }


            }

        });

        jButton3.setLabel("First");
        jButton3.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                    
                    if (rsall.first()){
                    
                    
                        jTextField1.setText(Integer.toString(rsall.getInt(1))); 
                        jTextField2.setText(rsall.getString(2)); 
                        jTextField3.setText(rsall.getString(3)); 
                        jTextField4.setText(rsall.getString(5));
                        jTextField5.setText(Double.toString(rsall.getDouble(9))); 
                    }


                } catch (SQLException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });

        jButton4.setLabel("Previous");
        jButton4.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                   
                    if (rsall.previous()){
                    
                    
                        jTextField1.setText(Integer.toString(rsall.getInt(1))); 
                        jTextField2.setText(rsall.getString(2)); 
                        jTextField3.setText(rsall.getString(3)); 
                        jTextField4.setText(rsall.getString(5));
                        jTextField5.setText(Double.toString(rsall.getDouble(9))); 
                    }


                } catch (SQLException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });

        jButton5.setLabel("Next");
        jButton5.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                    
                    if (rsall.next()){
                    
                    
                        jTextField1.setText(Integer.toString(rsall.getInt(1))); 
                        jTextField2.setText(rsall.getString(2)); 
                        jTextField3.setText(rsall.getString(3)); 
                        jTextField4.setText(rsall.getString(5));
                        jTextField5.setText(Double.toString(rsall.getDouble(9))); 
                    }


                } catch (SQLException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });

        jButton6.setLabel("Last");
        jButton6.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                   
                   if (rsall.last()){
                    
                    
                        jTextField1.setText(Integer.toString(rsall.getInt(1))); 
                        jTextField2.setText(rsall.getString(2)); 
                        jTextField3.setText(rsall.getString(3)); 
                        jTextField4.setText(rsall.getString(5));
                        jTextField5.setText(Double.toString(rsall.getDouble(9))); 
                    }
                   //jButton5.setEnabled(false);


                } catch (SQLException ex) {
                    Logger.getLogger(DBInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });
        jButton7.setLabel("Add");
        jButton7.addActionListener( new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                   if (!jTextField1.getText().equalsIgnoreCase("") &&
                           !jTextField2.getText().equalsIgnoreCase("") &&
                           !jTextField3.getText().equalsIgnoreCase("") &&
                           !jTextField4.getText().equalsIgnoreCase("") &&
                           !jTextField5.getText().equalsIgnoreCase("")){
                   
                        Student std = new Student (Integer.parseInt(jTextField1.getText()),
                                        jTextField2.getText(),
                                        jTextField3.getText(),
                                        jTextField4.getText(),
                                        Double.parseDouble(jTextField5.getText()));
                       StudentDB.add(std);
                   
                   
                   }
                   


                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } catch (ClassNotFoundException cnfe){
                
                    JOptionPane.showMessageDialog(null, cnfe.getMessage());
                
                }

            }

        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                            .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField1))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           



    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration                   
}
